name: Test Suite

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: "Fuzzy ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
